### CountVectorizer
Convert a collection of text documents to a matrix of token counts
- [sklearn.feature_extraction.text.CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)


In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset =["Eka thakar  cheye g0vir prem hote pare na na na",
        "nijer sathe kotha bolar cheye govir prem alap hote pare na",
        "This process is called feature extraction or vectorization" ]   

- [Using CountVectorizer to Extracting Features from Text | Geeksforgeeeks](https://www.geeksforgeeks.org/using-countvectorizer-to-extracting-features-from-text/)
- Every cell contains a number, that represents the count of the word in that particular text.
- All words have been converted to lowercase.
- The words in columns have been arranged alphabetically.

In [4]:

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(dataset)
vectorizer.get_feature_names()


# encode document
#vector = vectorizer.transform(text)
# summarize encoded vector
#print(vector.shape)
#print(vector.toarray())

['alap',
 'bolar',
 'called',
 'cheye',
 'eka',
 'extraction',
 'feature',
 'g0vir',
 'govir',
 'hote',
 'is',
 'kotha',
 'na',
 'nijer',
 'or',
 'pare',
 'prem',
 'process',
 'sathe',
 'thakar',
 'this',
 'vectorization']

In [5]:
X.toarray()

array([[0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 3, 0, 0, 1, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1]],
      dtype=int64)

In [6]:
vectorizer.vocabulary_

{'eka': 4,
 'thakar': 19,
 'cheye': 3,
 'g0vir': 7,
 'prem': 16,
 'hote': 9,
 'pare': 15,
 'na': 12,
 'nijer': 13,
 'sathe': 18,
 'kotha': 11,
 'bolar': 1,
 'govir': 8,
 'alap': 0,
 'this': 20,
 'process': 17,
 'is': 10,
 'called': 2,
 'feature': 6,
 'extraction': 5,
 'or': 14,
 'vectorization': 21}

In [7]:
# encode document
vector = vectorizer.transform(dataset)
#summarize encoded vector
print(vector.shape)
print(vector.toarray())

(3, 22)
[[0 0 0 1 1 0 0 1 0 1 0 0 3 0 0 1 1 0 0 1 0 0]
 [1 1 0 1 0 0 0 0 1 1 0 1 1 1 0 1 1 0 1 0 0 0]
 [0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1]]


In [8]:
df = pd.DataFrame(vector.toarray(), columns=vectorizer.get_feature_names())
df

alap  bolar  called  cheye  eka  extraction  feature  g0vir  govir  hote  \
0     0      0       0      1    1           0        0      1      0     1   
1     1      1       0      1    0           0        0      0      1     1   
2     0      0       1      0    0           1        1      0      0     0   

   ...  na  nijer  or  pare  prem  process  sathe  thakar  this  vectorization  
0  ...   3      0   0     1     1        0      0       1     0              0  
1  ...   1      1   0     1     1        0      1       0     0              0  
2  ...   0      0   1     0     0        1      0       0     1              1  

[3 rows x 22 columns]