<h2 style='color:purple' align='center'>Predicting survival from titanic crash</h2>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:

inputs = df.drop('Survived',axis='columns')
target = df.Survived


In [5]:
inputs

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [7]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [8]:
inputs.Sex.unique()

array(['male', 'female'], dtype=object)

In [9]:
import numpy as np
inputs["Sex"] = np.where(inputs["Sex"] == "male" , 1, 0)

In [10]:
inputs.Sex.unique()

array([1, 0])

In [11]:
inputs

Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [12]:
inputs.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [13]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [14]:
inputs.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [16]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [17]:
model.fit(X_train,y_train)

GaussianNB()

In [18]:
model.score(X_test,y_test)

0.7873134328358209

In [19]:
X_test[0:10]

Pclass  Sex        Age     Fare
185       1    1  29.699118  50.0000
653       3    0  29.699118   7.8292
287       3    1  22.000000   7.8958
545       1    1  64.000000  26.0000
807       3    0  18.000000   7.7750
30        1    1  40.000000  27.7208
870       3    1  26.000000   7.8958
733       2    1  23.000000  13.0000
405       2    1  34.000000  21.0000
631       3    1  51.000000   7.0542

In [20]:
y_test[0:10]

185    0
653    1
287    0
545    0
807    0
30     0
870    0
733    0
405    0
631    0
Name: Survived, dtype: int64

In [21]:
model.predict(X_test[0:10])

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [22]:
model.predict_proba(X_test[:10])

array([[0.66333616, 0.33666384],
       [0.39073882, 0.60926118],
       [0.95857564, 0.04142436],
       [0.67063599, 0.32936401],
       [0.32414475, 0.67585525],
       [0.75722318, 0.24277682],
       [0.96230937, 0.03769063],
       [0.91659735, 0.08340265],
       [0.92932873, 0.07067127],
       [0.96423053, 0.03576947]])

**Calculate the score using cross validation**

In [23]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.752     , 0.792     , 0.776     , 0.77419355, 0.78225806])